-- ============================================================================
-- baby01 — Supabase 전체 스키마 + 커뮤니티 정렬 + RLS(anon) 한 번에 적용
-- ============================================================================
-- 이 파일 = 다음 네 마이그레이션을 **순서대로** 합친 것이다.
--   20260225120000_app_domain_tables.sql
--   20260225140000_align_community_posts_comments.sql
--   20260225150000_rls_app_domain_anon.sql
--   20260225160000_content_topic_korean.sql  (topic 한글·기존 영문 데이터 치환 — 아래 [1a]에 편입)
-- SQL Editor에 **위→아래 한 번** 붙여넣어 실행하면 된다(이미 적용한 대상은 IF NOT EXISTS
-- / DROP IF EXISTS 덕에 대부분 멱등).
--
-- 절차 요약: app_users·content_topic_*·baby_records → posts·comments → RLS 전 테이블
-- 운영 전 RLS `USING (true)` 는 반드시 좁힌다.
-- ============================================================================

-- ---- [1/3] 회원 · 부모이야기·정보 · 토픽 댓글 · 아이기록 ----
-- [1a] content_topic_posts.topic: 아래 [1a 끝] 에서 CHECK 한 번으로 부모이야기|정보만 허용한다.
--     CREATE 절에 CHECK 를 넣지 않는 이유 — 신규 DB 에서 CREATE 직후 DROP/ADD 를 반복할 필요를 없애기 위함.

CREATE TABLE IF NOT EXISTS public.app_users (
  email text PRIMARY KEY,
  nickname text NOT NULL DEFAULT '',
  phone text NOT NULL DEFAULT '',
  password_hash text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  child_birth_year integer,
  child_count integer,
  child_birth_years integer[],
  child_birth_dates text[],
  child_names text[],
  primary_child_index integer DEFAULT 0
);

COMMENT ON TABLE public.app_users IS '로컬 users.json 을 옮기는 대상 — 자녀 배열은 PostgreSQL 배열/NULL 허용';

CREATE INDEX IF NOT EXISTS idx_app_users_created ON public.app_users (created_at DESC);

CREATE TABLE IF NOT EXISTS public.content_topic_posts (
  id text PRIMARY KEY,
  topic text NOT NULL,
  title text NOT NULL,
  content text NOT NULL,
  author_email text NOT NULL,
  author_nickname text NOT NULL DEFAULT '',
  view_count integer NOT NULL DEFAULT 0,
  password text,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT content_topic_posts_topic_check CHECK (topic = ANY (ARRAY['부모이야기'::text, '정보'::text]))
);

COMMENT ON TABLE public.content_topic_posts IS '부모이야기·정보 게시글 — id 는 앱 contentTopicPostStore 의 문자열 id';

CREATE INDEX IF NOT EXISTS idx_content_topic_posts_topic_created
  ON public.content_topic_posts (topic, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_content_topic_posts_author
  ON public.content_topic_posts (author_email);

-- [1a 끝] topic CHECK + 기존 영문 값 치환(마이그레이션 20260225160000 와 동일)
-- * 기존 DB 에 parentStories|info CHECK 가 있으면 먼저 뗀 뒤 UPDATE 해야 한글로 바뀐다.
-- * 신규 DB 는 아래 CHECK 가 곧 topic 제약이 된다(위 CREATE 에는 topic CHECK 를 넣지 않음).

ALTER TABLE public.content_topic_posts
  DROP CONSTRAINT IF EXISTS content_topic_posts_topic_check;

UPDATE public.content_topic_posts
SET topic = '부모이야기'
WHERE topic = 'parentStories';

UPDATE public.content_topic_posts
SET topic = '정보'
WHERE topic = 'info';

ALTER TABLE public.content_topic_posts
  ADD CONSTRAINT content_topic_posts_topic_check
  CHECK (topic = ANY (ARRAY['부모이야기'::text, '정보'::text]));

COMMENT ON CONSTRAINT content_topic_posts_topic_check ON public.content_topic_posts IS
  '부모이야기·정보 메뉴 구분 — 앱 ContentTopicKind 와 동일한 한글 리터럴';

CREATE TABLE IF NOT EXISTS public.content_topic_comments (
  id text PRIMARY KEY,
  post_id text NOT NULL REFERENCES public.content_topic_posts (id) ON DELETE CASCADE,
  content text NOT NULL,
  author_email text NOT NULL,
  author_nickname text NOT NULL DEFAULT '',
  parent_id text REFERENCES public.content_topic_comments (id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.content_topic_comments IS
  '부모이야기·정보 댓글. 커뮤니티 댓글은 public.comments(post_id=정수)에 별도.';

CREATE INDEX IF NOT EXISTS idx_content_topic_comments_post_created
  ON public.content_topic_comments (post_id, created_at);
CREATE INDEX IF NOT EXISTS idx_content_topic_comments_parent
  ON public.content_topic_comments (parent_id)
  WHERE parent_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS public.baby_records (
  id text PRIMARY KEY,
  author_email text NOT NULL,
  recorded_at timestamptz NOT NULL,
  child_index integer NOT NULL DEFAULT 0,
  weight_kg numeric,
  height_cm numeric,
  head_circumference_cm numeric,
  daily_note text NOT NULL DEFAULT ''
);

COMMENT ON TABLE public.baby_records IS '가정용 성장/일일 기록 — id 는 앱 babyRecordStore 와 동일한 문자열';

CREATE INDEX IF NOT EXISTS idx_baby_records_author_recorded
  ON public.baby_records (author_email, recorded_at DESC);

-- ---- [2/3] 커뮤니티 posts / comments (postStore · communityCommentStore) ----

CREATE TABLE IF NOT EXISTS public.posts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL DEFAULT '',
  content text,
  author_email text,
  nickname text,
  child_birth_year integer NOT NULL DEFAULT 0,
  category text,
  prefix text,
  view_count integer NOT NULL DEFAULT 0,
  edit_password text,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.posts ADD COLUMN IF NOT EXISTS title text;
ALTER TABLE public.posts ADD COLUMN IF NOT EXISTS content text;
ALTER TABLE public.posts ADD COLUMN IF NOT EXISTS author_email text;
ALTER TABLE public.posts ADD COLUMN IF NOT EXISTS nickname text;
ALTER TABLE public.posts ADD COLUMN IF NOT EXISTS child_birth_year integer;
ALTER TABLE public.posts ADD COLUMN IF NOT EXISTS category text;
ALTER TABLE public.posts ADD COLUMN IF NOT EXISTS prefix text;
ALTER TABLE public.posts ADD COLUMN IF NOT EXISTS view_count integer;
ALTER TABLE public.posts ADD COLUMN IF NOT EXISTS edit_password text;
ALTER TABLE public.posts ADD COLUMN IF NOT EXISTS created_at timestamptz;

ALTER TABLE public.posts
  ALTER COLUMN child_birth_year SET DEFAULT 0;
ALTER TABLE public.posts
  ALTER COLUMN view_count SET DEFAULT 0;
UPDATE public.posts
SET child_birth_year = 0
WHERE child_birth_year IS NULL;
UPDATE public.posts
SET view_count = 0
WHERE view_count IS NULL;
UPDATE public.posts
SET created_at = now()
WHERE created_at IS NULL;
ALTER TABLE public.posts
  ALTER COLUMN child_birth_year SET NOT NULL;
ALTER TABLE public.posts
  ALTER COLUMN view_count SET NOT NULL;
ALTER TABLE public.posts
  ALTER COLUMN created_at SET NOT NULL;
ALTER TABLE public.posts
  ALTER COLUMN created_at SET DEFAULT now();
ALTER TABLE public.posts
  ALTER COLUMN view_count SET DEFAULT 0;
ALTER TABLE public.posts
  ALTER COLUMN child_birth_year SET DEFAULT 0;

CREATE INDEX IF NOT EXISTS idx_posts_category_created
  ON public.posts (category, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_posts_author_email
  ON public.posts (author_email);

CREATE TABLE IF NOT EXISTS public.comments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id bigint NOT NULL,
  content text NOT NULL,
  author_email text,
  author_nickname text,
  parent_id bigint,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT comments_post_fk
    FOREIGN KEY (post_id) REFERENCES public.posts (id) ON DELETE CASCADE,
  CONSTRAINT comments_parent_fk
    FOREIGN KEY (parent_id) REFERENCES public.comments (id) ON DELETE CASCADE
);

ALTER TABLE public.comments ADD COLUMN IF NOT EXISTS post_id bigint;
ALTER TABLE public.comments ADD COLUMN IF NOT EXISTS content text;
ALTER TABLE public.comments ADD COLUMN IF NOT EXISTS author_email text;
ALTER TABLE public.comments ADD COLUMN IF NOT EXISTS author_nickname text;
ALTER TABLE public.comments ADD COLUMN IF NOT EXISTS parent_id bigint;
ALTER TABLE public.comments ADD COLUMN IF NOT EXISTS created_at timestamptz;

UPDATE public.comments
SET content = coalesce(content, '')
WHERE content IS NULL;
UPDATE public.comments
SET created_at = now()
WHERE created_at IS NULL;
ALTER TABLE public.comments
  ALTER COLUMN created_at SET NOT NULL;
ALTER TABLE public.comments
  ALTER COLUMN created_at SET DEFAULT now();

CREATE INDEX IF NOT EXISTS idx_comments_post_created
  ON public.comments (post_id, created_at);
CREATE INDEX IF NOT EXISTS idx_comments_parent
  ON public.comments (parent_id)
  WHERE parent_id IS NOT NULL;

DO $fk$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'comments_post_fk' AND conrelid = 'public.comments'::regclass) THEN
    ALTER TABLE public.comments
      ADD CONSTRAINT comments_post_fk
      FOREIGN KEY (post_id) REFERENCES public.posts (id) ON DELETE CASCADE;
  END IF;
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'comments_post_fk 생략(또는 이미 있음/데이터 불일치): %', SQLERRM;
END;
$fk$;

DO $fkt$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'comments_parent_fk' AND conrelid = 'public.comments'::regclass) THEN
    ALTER TABLE public.comments
      ADD CONSTRAINT comments_parent_fk
      FOREIGN KEY (parent_id) REFERENCES public.comments (id) ON DELETE CASCADE;
  END IF;
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'comments_parent_fk 생략(또는 이미 있음/데이터 불일치): %', SQLERRM;
END;
$fkt$;

-- 커뮤니티 RLS
ALTER TABLE public.posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.comments ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Anyone can update posts" ON public.posts;

DROP POLICY IF EXISTS "app_posts_all_anon" ON public.posts;
CREATE POLICY "app_posts_all_anon"
  ON public.posts
  FOR ALL
  USING (true)
  WITH CHECK (true);

DROP POLICY IF EXISTS "app_comments_all_anon" ON public.comments;
CREATE POLICY "app_comments_all_anon"
  ON public.comments
  FOR ALL
  USING (true)
  WITH CHECK (true);

-- ---- [3/3] app_users · content_topic_* · baby_records RLS ----

ALTER TABLE public.app_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.content_topic_posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.content_topic_comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.baby_records ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "app_users_all_anon" ON public.app_users;
CREATE POLICY "app_users_all_anon" ON public.app_users FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "content_topic_posts_all_anon" ON public.content_topic_posts;
CREATE POLICY "content_topic_posts_all_anon" ON public.content_topic_posts FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "content_topic_comments_all_anon" ON public.content_topic_comments;
CREATE POLICY "content_topic_comments_all_anon" ON public.content_topic_comments FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "baby_records_all_anon" ON public.baby_records;
CREATE POLICY "baby_records_all_anon" ON public.baby_records FOR ALL USING (true) WITH CHECK (true);
