-- ============================================================================
-- baby01 — Supabase 전체 스키마 + 커뮤니티 정렬 + RLS(anon) 한 번에 적용 (최종본)
-- ============================================================================
-- * 최종본 정리: posts.latitude/longitude 중복 ADD COLUMN 제거, pattern_logs·요약 조회 주석 보강.
-- 이 파일 = 다음 **여섯** 마이그레이션을 **순서대로** 합친 것이다.
--   20260225120000_app_domain_tables.sql
--   20260225140000_align_community_posts_comments.sql
--   20260225150000_rls_app_domain_anon.sql
--   20260225160000_content_topic_korean.sql  (topic 한글·기존 영문 데이터 치환 — 아래 [1a]에 편입)
--   20260427120000_posts_latitude_longitude.sql  (지역 게시판: posts.latitude/longitude + 인덱스)
--   20260429130000_pattern_logs.sql  (패턴 기록 pattern_logs — 요약 바 category_id 규칙 동일)
-- SQL Editor에 **위→아래 한 번** 붙여넣어 실행하면 된다(이미 적용한 대상은 IF NOT EXISTS
-- / DROP IF EXISTS 덕에 대부분 멱등).
--
-- 절차 요약: app_users·content_topic_*·baby_records → posts·comments → RLS 전 테이블
-- → posts 에 지역용 좌표 컬럼(지역1km 목록·필터는 앱 API에서 Haversine 처리)
-- 운영 전 RLS `USING (true)` 는 반드시 좁힌다.
-- ============================================================================

-- ---- [1/3] 회원 · 부모이야기·정보 · 토픽 댓글 · 아이기록 ----
-- [1a] content_topic_posts.topic: 아래에서 CHECK 를 잠시 제거한 뒤 영문 topic 을 한글로 치환하고,
--      다시 부모이야기|정보만 허용하도록 CHECK 를 붙인다(기존 DB·신규 DB 공통 멱등 절차).

CREATE TABLE IF NOT EXISTS public.app_users (
  email text PRIMARY KEY,
  nickname text NOT NULL DEFAULT '',
  phone text NOT NULL DEFAULT '',
  password_hash text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  child_birth_year integer,
  child_count integer,
  child_birth_years integer[],
  child_birth_dates text[],
  child_names text[],
  primary_child_index integer DEFAULT 0
);

COMMENT ON TABLE public.app_users IS '로컬 users.json 을 옮기는 대상 — 자녀 배열은 PostgreSQL 배열/NULL 허용';

CREATE INDEX IF NOT EXISTS idx_app_users_created ON public.app_users (created_at DESC);

CREATE TABLE IF NOT EXISTS public.content_topic_posts (
  id text PRIMARY KEY,
  topic text NOT NULL,
  title text NOT NULL,
  content text NOT NULL,
  author_email text NOT NULL,
  author_nickname text NOT NULL DEFAULT '',
  view_count integer NOT NULL DEFAULT 0,
  password text,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT content_topic_posts_topic_check CHECK (topic = ANY (ARRAY['부모이야기'::text, '정보'::text]))
);

COMMENT ON TABLE public.content_topic_posts IS '부모이야기·정보 게시글 — id 는 앱 contentTopicPostStore 의 문자열 id';

CREATE INDEX IF NOT EXISTS idx_content_topic_posts_topic_created
  ON public.content_topic_posts (topic, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_content_topic_posts_author
  ON public.content_topic_posts (author_email);

-- [1a 끝] topic CHECK + 기존 영문 값 치환(마이그레이션 20260225160000 와 동일)
-- * 기존 DB 에 parentStories|info 가 있으면 아래 UPDATE 로 한글로 맞춘다.

ALTER TABLE public.content_topic_posts
  DROP CONSTRAINT IF EXISTS content_topic_posts_topic_check;

UPDATE public.content_topic_posts
SET topic = '부모이야기'
WHERE topic = 'parentStories';

UPDATE public.content_topic_posts
SET topic = '정보'
WHERE topic = 'info';

ALTER TABLE public.content_topic_posts
  ADD CONSTRAINT content_topic_posts_topic_check
  CHECK (topic = ANY (ARRAY['부모이야기'::text, '정보'::text]));

COMMENT ON CONSTRAINT content_topic_posts_topic_check ON public.content_topic_posts IS
  '부모이야기·정보 메뉴 구분 — 앱 ContentTopicKind 와 동일한 한글 리터럴';

CREATE TABLE IF NOT EXISTS public.content_topic_comments (
  id text PRIMARY KEY,
  post_id text NOT NULL REFERENCES public.content_topic_posts (id) ON DELETE CASCADE,
  content text NOT NULL,
  author_email text NOT NULL,
  author_nickname text NOT NULL DEFAULT '',
  parent_id text REFERENCES public.content_topic_comments (id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.content_topic_comments IS
  '부모이야기·정보 댓글. 커뮤니티 댓글은 public.comments(post_id=정수)에 별도.';

CREATE INDEX IF NOT EXISTS idx_content_topic_comments_post_created
  ON public.content_topic_comments (post_id, created_at);
CREATE INDEX IF NOT EXISTS idx_content_topic_comments_parent
  ON public.content_topic_comments (parent_id)
  WHERE parent_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS public.baby_records (
  id text PRIMARY KEY,
  author_email text NOT NULL,
  recorded_at timestamptz NOT NULL,
  child_index integer NOT NULL DEFAULT 0,
  weight_kg numeric,
  height_cm numeric,
  head_circumference_cm numeric,
  daily_note text NOT NULL DEFAULT ''
);

COMMENT ON TABLE public.baby_records IS '가정용 성장/일일 기록 — id 는 앱 babyRecordStore 와 동일한 문자열';

CREATE INDEX IF NOT EXISTS idx_baby_records_author_recorded
  ON public.baby_records (author_email, recorded_at DESC);

-- ---- [2/3] 커뮤니티 posts / comments (postStore · communityCommentStore) ----

CREATE TABLE IF NOT EXISTS public.posts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL DEFAULT '',
  content text,
  author_email text,
  nickname text,
  child_birth_year integer NOT NULL DEFAULT 0,
  category text,
  prefix text,
  view_count integer NOT NULL DEFAULT 0,
  edit_password text,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.posts ADD COLUMN IF NOT EXISTS title text;
ALTER TABLE public.posts ADD COLUMN IF NOT EXISTS content text;
ALTER TABLE public.posts ADD COLUMN IF NOT EXISTS author_email text;
ALTER TABLE public.posts ADD COLUMN IF NOT EXISTS nickname text;
ALTER TABLE public.posts ADD COLUMN IF NOT EXISTS child_birth_year integer;
ALTER TABLE public.posts ADD COLUMN IF NOT EXISTS category text;
ALTER TABLE public.posts ADD COLUMN IF NOT EXISTS prefix text;
ALTER TABLE public.posts ADD COLUMN IF NOT EXISTS view_count integer;
ALTER TABLE public.posts ADD COLUMN IF NOT EXISTS edit_password text;
ALTER TABLE public.posts ADD COLUMN IF NOT EXISTS created_at timestamptz;

-- 지역 1km 게시판: 작성 시점 좌표(목록은 독자 위치 기준 반경 필터 — postStore)
ALTER TABLE public.posts ADD COLUMN IF NOT EXISTS latitude double precision;
ALTER TABLE public.posts ADD COLUMN IF NOT EXISTS longitude double precision;

COMMENT ON COLUMN public.posts.latitude IS '지역1km 게시글일 때 작성 위치 위도';
COMMENT ON COLUMN public.posts.longitude IS '지역1km 게시글일 때 작성 위치 경도';

ALTER TABLE public.posts
  ALTER COLUMN child_birth_year SET DEFAULT 0;
ALTER TABLE public.posts
  ALTER COLUMN view_count SET DEFAULT 0;
UPDATE public.posts
SET child_birth_year = 0
WHERE child_birth_year IS NULL;
UPDATE public.posts
SET view_count = 0
WHERE view_count IS NULL;
UPDATE public.posts
SET created_at = now()
WHERE created_at IS NULL;
ALTER TABLE public.posts
  ALTER COLUMN child_birth_year SET NOT NULL;
ALTER TABLE public.posts
  ALTER COLUMN view_count SET NOT NULL;
ALTER TABLE public.posts
  ALTER COLUMN created_at SET NOT NULL;
ALTER TABLE public.posts
  ALTER COLUMN created_at SET DEFAULT now();
ALTER TABLE public.posts
  ALTER COLUMN view_count SET DEFAULT 0;
ALTER TABLE public.posts
  ALTER COLUMN child_birth_year SET DEFAULT 0;

CREATE INDEX IF NOT EXISTS idx_posts_category_created
  ON public.posts (category, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_posts_author_email
  ON public.posts (author_email);

CREATE TABLE IF NOT EXISTS public.comments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id bigint NOT NULL,
  content text NOT NULL,
  author_email text,
  author_nickname text,
  parent_id bigint,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT comments_post_fk
    FOREIGN KEY (post_id) REFERENCES public.posts (id) ON DELETE CASCADE,
  CONSTRAINT comments_parent_fk
    FOREIGN KEY (parent_id) REFERENCES public.comments (id) ON DELETE CASCADE
);

ALTER TABLE public.comments ADD COLUMN IF NOT EXISTS post_id bigint;
ALTER TABLE public.comments ADD COLUMN IF NOT EXISTS content text;
ALTER TABLE public.comments ADD COLUMN IF NOT EXISTS author_email text;
ALTER TABLE public.comments ADD COLUMN IF NOT EXISTS author_nickname text;
ALTER TABLE public.comments ADD COLUMN IF NOT EXISTS parent_id bigint;
ALTER TABLE public.comments ADD COLUMN IF NOT EXISTS created_at timestamptz;

UPDATE public.comments
SET content = coalesce(content, '')
WHERE content IS NULL;
UPDATE public.comments
SET created_at = now()
WHERE created_at IS NULL;
ALTER TABLE public.comments
  ALTER COLUMN created_at SET NOT NULL;
ALTER TABLE public.comments
  ALTER COLUMN created_at SET DEFAULT now();

CREATE INDEX IF NOT EXISTS idx_comments_post_created
  ON public.comments (post_id, created_at);
CREATE INDEX IF NOT EXISTS idx_comments_parent
  ON public.comments (parent_id)
  WHERE parent_id IS NOT NULL;

DO $fk$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'comments_post_fk' AND conrelid = 'public.comments'::regclass) THEN
    ALTER TABLE public.comments
      ADD CONSTRAINT comments_post_fk
      FOREIGN KEY (post_id) REFERENCES public.posts (id) ON DELETE CASCADE;
  END IF;
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'comments_post_fk 생략(또는 이미 있음/데이터 불일치): %', SQLERRM;
END;
$fk$;

DO $fkt$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'comments_parent_fk' AND conrelid = 'public.comments'::regclass) THEN
    ALTER TABLE public.comments
      ADD CONSTRAINT comments_parent_fk
      FOREIGN KEY (parent_id) REFERENCES public.comments (id) ON DELETE CASCADE;
  END IF;
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'comments_parent_fk 생략(또는 이미 있음/데이터 불일치): %', SQLERRM;
END;
$fkt$;

-- 커뮤니티 RLS
ALTER TABLE public.posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.comments ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Anyone can update posts" ON public.posts;

DROP POLICY IF EXISTS "app_posts_all_anon" ON public.posts;
CREATE POLICY "app_posts_all_anon"
  ON public.posts
  FOR ALL
  USING (true)
  WITH CHECK (true);

DROP POLICY IF EXISTS "app_comments_all_anon" ON public.comments;
CREATE POLICY "app_comments_all_anon"
  ON public.comments
  FOR ALL
  USING (true)
  WITH CHECK (true);

-- ---- [3/3] app_users · content_topic_* · baby_records RLS ----

ALTER TABLE public.app_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.content_topic_posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.content_topic_comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.baby_records ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "app_users_all_anon" ON public.app_users;
CREATE POLICY "app_users_all_anon" ON public.app_users FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "content_topic_posts_all_anon" ON public.content_topic_posts;
CREATE POLICY "content_topic_posts_all_anon" ON public.content_topic_posts FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "content_topic_comments_all_anon" ON public.content_topic_comments;
CREATE POLICY "content_topic_comments_all_anon" ON public.content_topic_comments FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "baby_records_all_anon" ON public.baby_records;
CREATE POLICY "baby_records_all_anon" ON public.baby_records FOR ALL USING (true) WITH CHECK (true);

-- ---- +지역 게시판(지역1km) — `posts` 한 테이블(마이그레이션 20260427120000 요약) ----
-- * 앱: `src/lib/postStore.ts` — 지역 글은 `category = '지역1km'`, `prefix` 에 유형(고민·정보공유…).
-- * `latitude`·`longitude` 컬럼은 위 [2/3] posts 절에서 한 번만 ADD COLUMN 한다(중복 없음).
-- * 목록은 클라이언트 위치 기준 1km 필터(Haversine); DB 는 부분 인덱스로 조회에만 보조.
-- * SQL Editor 예: SELECT id, title, category, prefix, latitude, longitude, created_at
--   FROM public.posts WHERE category = '지역1km' ORDER BY created_at DESC;

CREATE INDEX IF NOT EXISTS idx_posts_category_region
  ON public.posts (category, created_at DESC)
  WHERE category = '지역1km';

-- ---- 패턴 기록(pattern_logs) — 마이그레이션 20260429130000_pattern_logs.sql 과 동일 ----
CREATE TABLE IF NOT EXISTS public.pattern_logs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_email text NOT NULL,
  log_id text NOT NULL,
  category_id text NOT NULL,
  label text NOT NULL,
  at_ms bigint NOT NULL,
  child_index smallint NOT NULL DEFAULT 0 CHECK (child_index >= 0 AND child_index <= 4),
  memo text,
  breast text CHECK (breast IS NULL OR breast IN ('left', 'right', 'both')),
  duration_min numeric,
  ml_amount numeric,
  weaning_type text,
  diaper_type text CHECK (diaper_type IS NULL OR diaper_type IN ('pee', 'poo', 'both')),
  sleep_type text CHECK (sleep_type IS NULL OR sleep_type IN ('night', 'nap')),
  pump_ml_left numeric,
  pump_ml_right numeric,
  hospital_type text CHECK (hospital_type IS NULL OR hospital_type IN ('checkup', 'illness')),
  hospital_name text,
  hospital_doctor text,
  hospital_note text,
  temp_c numeric,
  med_name text,
  snack_name text,
  snack_amount numeric,
  snack_unit text CHECK (snack_unit IS NULL OR snack_unit IN ('ml', 'g')),
  play_name text,
  play_reaction text CHECK (
    play_reaction IS NULL OR play_reaction IN ('like', 'less-interest')
  ),
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT pattern_logs_log_id_key UNIQUE (log_id)
);

COMMENT ON TABLE public.pattern_logs IS
  '패턴 기록 — 앱 PatternLogEntry(logId→log_id, atMs→at_ms, authorEmail→user_email)';
COMMENT ON COLUMN public.pattern_logs.log_id IS '앱 문자열 logId — 유일(같은 기록 수정·재전송 시 충돌 방지)';
COMMENT ON COLUMN public.pattern_logs.at_ms IS '기록 시각 epoch ms — UI “N분 전” 과 동일 기준';
COMMENT ON COLUMN public.pattern_logs.category_id IS
  '앱 categoryId 영문 키 — 헤더 칩: diaper|weaning|sleep|moyu|bunyu|pumpFeed|milk 등; 요약 바(마지막 기저귀·수유·잠)는 diaper / (moyu,pumpFeed) / (bunyu,milk) / sleep';

CREATE INDEX IF NOT EXISTS idx_pattern_logs_user_child_at
  ON public.pattern_logs (user_email, child_index, at_ms DESC);

CREATE INDEX IF NOT EXISTS idx_pattern_logs_user_child_cat_at
  ON public.pattern_logs (user_email, child_index, category_id, at_ms DESC);

ALTER TABLE public.pattern_logs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "pattern_logs_all_anon" ON public.pattern_logs;
CREATE POLICY "pattern_logs_all_anon"
  ON public.pattern_logs
  FOR ALL
  USING (true)
  WITH CHECK (true);

-- ---- pattern_logs: 조회 예시 ----
-- * 실행용 전체: `supabase/pattern_logs_last_summary.sql`
-- * :user_email, :child_index 는 바인딩하거나 문자열·숫자 리터럴로 치환.
-- * 요약 바(패턴 기록 화면): 모유·유축 줄 moyu+pumpFeed, 분유·유즙 줄 bunyu+milk.
-- * 네비 헤더 “수유” 칩만 쿼리할 때: category_id IN ('pumpFeed','milk') 최신 1건(앱 Navbar 와 동일).

-- [단건] 마지막 기저귀
-- SELECT log_id, at_ms, diaper_type, memo
-- FROM public.pattern_logs
-- WHERE user_email = :user_email AND child_index = :child_index AND category_id = 'diaper'
-- ORDER BY at_ms DESC
-- LIMIT 1;

-- [단건] 마지막 모유·유축(moyu / pumpFeed 중 더 최근)
-- SELECT log_id, category_id, at_ms, breast, duration_min, memo
-- FROM public.pattern_logs
-- WHERE user_email = :user_email AND child_index = :child_index
--   AND category_id IN ('moyu', 'pumpFeed')
-- ORDER BY at_ms DESC
-- LIMIT 1;

-- [단건] 마지막 분유·유즙(bunyu / milk 중 더 최근)
-- SELECT log_id, category_id, at_ms, ml_amount, memo
-- FROM public.pattern_logs
-- WHERE user_email = :user_email AND child_index = :child_index
--   AND category_id IN ('bunyu', 'milk')
-- ORDER BY at_ms DESC
-- LIMIT 1;

-- [단건] 마지막 잠
-- SELECT log_id, at_ms, sleep_type, duration_min, memo
-- FROM public.pattern_logs
-- WHERE user_email = :user_email AND child_index = :child_index AND category_id = 'sleep'
-- ORDER BY at_ms DESC
-- LIMIT 1;

-- [한 번에] 요약 바 4슬롯(JSON 컬럼 4개 — API 한 방 응답용)
-- WITH p AS (
--   SELECT 'user@example.com'::text AS user_email, 0::smallint AS child_index
-- )
-- SELECT
--   (SELECT row_to_json(t) FROM (
--     SELECT log_id, category_id, at_ms, diaper_type, memo
--     FROM public.pattern_logs r, p
--     WHERE r.user_email = p.user_email AND r.child_index = p.child_index
--       AND r.category_id = 'diaper'
--     ORDER BY r.at_ms DESC LIMIT 1
--   ) t) AS last_diaper,
--   (SELECT row_to_json(t) FROM (
--     SELECT log_id, category_id, at_ms, breast, duration_min, memo
--     FROM public.pattern_logs r, p
--     WHERE r.user_email = p.user_email AND r.child_index = p.child_index
--       AND r.category_id IN ('moyu', 'pumpFeed')
--     ORDER BY r.at_ms DESC LIMIT 1
--   ) t) AS last_feed_moyu_pump,
--   (SELECT row_to_json(t) FROM (
--     SELECT log_id, category_id, at_ms, ml_amount, memo
--     FROM public.pattern_logs r, p
--     WHERE r.user_email = p.user_email AND r.child_index = p.child_index
--       AND r.category_id IN ('bunyu', 'milk')
--     ORDER BY r.at_ms DESC LIMIT 1
--   ) t) AS last_feed_bunyu_milk,
--   (SELECT row_to_json(t) FROM (
--     SELECT log_id, category_id, at_ms, sleep_type, duration_min, memo
--     FROM public.pattern_logs r, p
--     WHERE r.user_email = p.user_email AND r.child_index = p.child_index
--       AND r.category_id = 'sleep'
--     ORDER BY r.at_ms DESC LIMIT 1
--   ) t) AS last_sleep;
