-- ============================================================================
-- 커뮤니티(아기이야기·꼬꼬마) — public.posts / public.comments
-- 앱 소스: src/lib/postStore.ts, src/lib/communityCommentStore.ts
-- Supabase SQL Editor 에서 1회 실행(이미 일부 컬럼이 있어도 IF NOT EXISTS 로 보완)
-- ============================================================================
-- posts 필수 개념:
--   - category: '아기이야기' | '꼬꼬마'  (getPostsByBoardKind·필터)
--   - nickname: 글쓴이 닉  (author_nickname 이 아님)
--   - child_birth_year, prefix, view_count, edit_password
-- comments 필수:
--   - post_id → posts.id (정수, bigint)
--   - author_nickname  (댓글 insert 에 반드시 포함)
--   - parent_id: 대댓글이면 부모 댓글 id (같은 테이블 id)
-- ============================================================================

-- ---------------------------------------------------------------------------
-- 1) posts: 뼈대가 없을 때만 전체 생성
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.posts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL DEFAULT '',
  content text,
  author_email text,
  -- 앱 read/insert: row.nickname — 반드시 이 이름(작성자 닉네임)
  nickname text,
  child_birth_year integer NOT NULL DEFAULT 0,
  -- boardKind 는 DB 에서 category 문자열로 저장 (아기이야기, 꼬꼬마)
  category text,
  prefix text,
  view_count integer NOT NULL DEFAULT 0,
  edit_password text,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- 이미 posts 가 있는 경우(컬럼만 부족): 없는 것만 덧붙임
ALTER TABLE public.posts ADD COLUMN IF NOT EXISTS title text;
ALTER TABLE public.posts ADD COLUMN IF NOT EXISTS content text;
ALTER TABLE public.posts ADD COLUMN IF NOT EXISTS author_email text;
ALTER TABLE public.posts ADD COLUMN IF NOT EXISTS nickname text;
ALTER TABLE public.posts ADD COLUMN IF NOT EXISTS child_birth_year integer;
ALTER TABLE public.posts ADD COLUMN IF NOT EXISTS category text;
ALTER TABLE public.posts ADD COLUMN IF NOT EXISTS prefix text;
ALTER TABLE public.posts ADD COLUMN IF NOT EXISTS view_count integer;
ALTER TABLE public.posts ADD COLUMN IF NOT EXISTS edit_password text;
ALTER TABLE public.posts ADD COLUMN IF NOT EXISTS created_at timestamptz;

-- NOT NULL / 기본값(기존 null 행이 있으면 한 번에 실행)
ALTER TABLE public.posts
  ALTER COLUMN child_birth_year SET DEFAULT 0;
ALTER TABLE public.posts
  ALTER COLUMN view_count SET DEFAULT 0;
UPDATE public.posts
SET child_birth_year = 0
WHERE child_birth_year IS NULL;
UPDATE public.posts
SET view_count = 0
WHERE view_count IS NULL;
UPDATE public.posts
SET created_at = now()
WHERE created_at IS NULL;
ALTER TABLE public.posts
  ALTER COLUMN child_birth_year SET NOT NULL;
ALTER TABLE public.posts
  ALTER COLUMN view_count SET NOT NULL;
ALTER TABLE public.posts
  ALTER COLUMN created_at SET NOT NULL;
ALTER TABLE public.posts
  ALTER COLUMN created_at SET DEFAULT now();
ALTER TABLE public.posts
  ALTER COLUMN view_count SET DEFAULT 0;
ALTER TABLE public.posts
  ALTER COLUMN child_birth_year SET DEFAULT 0;

CREATE INDEX IF NOT EXISTS idx_posts_category_created
  ON public.posts (category, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_posts_author_email
  ON public.posts (author_email);

-- ---------------------------------------------------------------------------
-- 2) comments: posts.id (bigint) 와 연결
--    기존 테이블이 post_id 타입이 다르면(예: text) 수동 점검 필요
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.comments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id bigint NOT NULL,
  content text NOT NULL,
  author_email text,
  -- 앱 insert 필드명 — post 의 nickname 과 구분(댓글만 author_nickname)
  author_nickname text,
  parent_id bigint,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT comments_post_fk
    FOREIGN KEY (post_id) REFERENCES public.posts (id) ON DELETE CASCADE,
  CONSTRAINT comments_parent_fk
    FOREIGN KEY (parent_id) REFERENCES public.comments (id) ON DELETE CASCADE
);

-- 테이블은 있었는데 제약/컬럼만 덜 쓴 경우(제약이 이미 있으면 이 블록은 실패할 수 있어 주석 권장)
-- 실패 시: 대시보드에서 FK / 컬럼을 맞춘 뒤 다시 시도
ALTER TABLE public.comments ADD COLUMN IF NOT EXISTS post_id bigint;
ALTER TABLE public.comments ADD COLUMN IF NOT EXISTS content text;
ALTER TABLE public.comments ADD COLUMN IF NOT EXISTS author_email text;
ALTER TABLE public.comments ADD COLUMN IF NOT EXISTS author_nickname text;
ALTER TABLE public.comments ADD COLUMN IF NOT EXISTS parent_id bigint;
ALTER TABLE public.comments ADD COLUMN IF NOT EXISTS created_at timestamptz;

UPDATE public.comments
SET content = coalesce(content, '')
WHERE content IS NULL;
-- content 가 NOT NULL 이어야 하면(데이터 꼬임 방지) 아래를 풀고 조정
-- ALTER TABLE public.comments ALTER COLUMN content SET NOT NULL;
UPDATE public.comments
SET created_at = now()
WHERE created_at IS NULL;
ALTER TABLE public.comments
  ALTER COLUMN created_at SET NOT NULL;
ALTER TABLE public.comments
  ALTER COLUMN created_at SET DEFAULT now();

CREATE INDEX IF NOT EXISTS idx_comments_post_created
  ON public.comments (post_id, created_at);
CREATE INDEX IF NOT EXISTS idx_comments_parent
  ON public.comments (parent_id)
  WHERE parent_id IS NOT NULL;

-- posts 가 먼저 있었고 comments 만 예전에 만들어진 경우, FK 를 수동으로 붙인다(데이터·타입이 맞을 때만 성공)
DO $fk$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'comments_post_fk' AND conrelid = 'public.comments'::regclass) THEN
    ALTER TABLE public.comments
      ADD CONSTRAINT comments_post_fk
      FOREIGN KEY (post_id) REFERENCES public.posts (id) ON DELETE CASCADE;
  END IF;
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'comments_post_fk 생략(또는 이미 있음/데이터 불일치): %', SQLERRM;
END;
$fk$;

DO $fkt$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'comments_parent_fk' AND conrelid = 'public.comments'::regclass) THEN
    ALTER TABLE public.comments
      ADD CONSTRAINT comments_parent_fk
      FOREIGN KEY (parent_id) REFERENCES public.comments (id) ON DELETE CASCADE;
  END IF;
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'comments_parent_fk 생략(또는 이미 있음/데이터 불일치): %', SQLERRM;
END;
$fkt$;

-- ---------------------------------------------------------------------------
-- 3) RLS: anon(공개) 키로 API 를 쓰는 경우, 정책이 없으면 막힌다.
--    운영 전에는 true 정책을 좁혀서 반드시 교체할 것.
-- ---------------------------------------------------------------------------
ALTER TABLE public.posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.comments ENABLE ROW LEVEL SECURITY;

-- 예전 SQL Editor 시도로 남은 UPDATE 전용 정책(겹침·혼란 방지)
DROP POLICY IF EXISTS "Anyone can update posts" ON public.posts;

DROP POLICY IF EXISTS "app_posts_all_anon" ON public.posts;
CREATE POLICY "app_posts_all_anon"
  ON public.posts
  FOR ALL
  USING (true)
  WITH CHECK (true);

DROP POLICY IF EXISTS "app_comments_all_anon" ON public.comments;
CREATE POLICY "app_comments_all_anon"
  ON public.comments
  FOR ALL
  USING (true)
  WITH CHECK (true);
